# # Definitions of tags to detect
#
# ## General remarks
#
# - All length in meters
# - 'size' refers to the length of the shared border between solid black and solid white rectangle.
#   See README.md or https://github.com/AprilRobotics/apriltag/wiki/AprilTag-User-Guide#pose-estimation for details.
# - Ellipsis (...) signifies that the previous element can be repeated multiple times.
#
# ## Standalone tag definitions
# ### Remarks
#
# - name is optional
#
# ### Syntax
#
# standalone_tags:
#   [
#     {id: ID, size: SIZE, name: NAME},
#     ...
#   ]
standalone_tags:
  [{id: 1, size: 0.1, name: Tag01},
    {id: 2, size: 0.1, name: Tag02},
    {id: 3, size: 0.1, name: Tag03},
    {id: 4, size: 0.1, name: Tag04},
    {id: 5, size: 0.1, name: Tag05},
    {id: 6, size: 0.1, name: Tag06},
    {id: 7, size: 0.1, name: Tag07},
    {id: 8, size: 0.1, name: Tag08},
    {id: 9, size: 0.1, name: Tag09},
    {id: 10, size: 0.1, name: Tag10},
    {id: 11, size: 0.1, name: Tag11},
    {id: 0, size: 0.1, name: Tag0}
  ]
# ## Tag bundle definitions
# ### Remarks
#
# - name is optional
# - x, y, z have default values of 0 thus they are optional
# - qw has default value of 1 and qx, qy, qz have default values of 0 thus they are optional
#
# ### Syntax
#
# tag_bundles:
#   [
#     {
#       name: 'CUSTOM_BUNDLE_NAME',
#       layout:
#         [
#           {id: ID, size: SIZE, x: X_POS, y: Y_POS, z: Z_POS, qw: QUAT_W_VAL, qx: QUAT_X_VAL, qy: QUAT_Y_VAL, qz: QUAT_Z_VAL},
#           ...
#         ]
#     },
#     ...
#   ]
tag_bundles:
  [
  ]
